version: "2.1"
services:
  client:
    build:
      context: ../
      dockerfile: Dockerfile
    command: ["node_modules/.bin/nodemon", "server/server/index.js"]
    environment:
      - NODE_ENV=development
    volumes:
      - ../:/app
      - static:/app/static_local/static

volumes:
  static:
  secrets:
  proxy_config: