version: "2.1"
services:

  client:
    # command: ["node", "server.js"]
    # image: node:9-alpine
    build:
      context: ../
      dockerfile: Dockerfile
    volumes:
      - ../:/app
      - static:/app/static_local/static
    # working_dir: /app

volumes:
  static:
  secrets:
  proxy_config: