version: "2.1"

services:
  client:
    image: node:9-alpine
    command: ["node_modules/.bin/nodemon", "server/server/index.js"]
    depends_on:
      - watch
      - watch-server
    environment:
      - NODE_ENV=development
    expose:
      - "3000"
    ports:
      - "3000:3000"
    user: node
    volumes:
      - ../:/app
      - static:/app/static_local/static
      - ../../huc-ui-components:/app/node_modules/huc-ui-components
      - ../../pergamon-ui-components:/app/node_modules/pergamon-ui-components
      - ../../timeline:/app/node_modules/timeline
    working_dir: /app

  watch:
    image: node:9-alpine
    command: ["npm", "run", "watch"]
    user: node
    volumes:
      - ../:/app
      - ../../huc-ui-components:/app/node_modules/huc-ui-components
      - ../../pergamon-ui-components:/app/node_modules/pergamon-ui-components
      - ../../timeline:/app/node_modules/timeline
    working_dir: /app
    working_dir: /app

  watch-server:
    image: node:9-alpine
    command: ["npm", "run", "watch.server"]
    user: node
    volumes:
      - ../:/app
      - ../../huc-ui-components:/app/node_modules/huc-ui-components
      - ../../pergamon-ui-components:/app/node_modules/pergamon-ui-components
      - ../../timeline:/app/node_modules/timeline
    working_dir: /app
    working_dir: /app

volumes:
  static:
  secrets:
  proxy_config: