version: "2.1"
services:
  client:
    build:
      context: ../
      dockerfile: docker/Dockerfile-dev
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ../:/app
      - static:/app/static

volumes:
  static: