version: '2.1'

services:
  client:
    image: huygensing/e-pistolarium-client
    ports:
      - "80:80"
    restart: always

  janus:
    image: huygensing/janus
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "8080:8080"
    entrypoint:
      ["/usr/local/bin/janus", "server", "config-docker-compose.yml"]

  elasticsearch:
    image: huygensing/elasticsearch-tiny
    healthcheck:
      test: "nc localhost 9300 < /dev/null"
      interval: 10s
      timeout: 3s
      retries: 5
    expose:
      - "9300"

  topmod:
    image: huygensing/topmod
    expose:
      - "8080"
